name: CI

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  Run-UTS:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "Hello CI"
    - name: Build
      run: ./scripts/build.sh
    - name: Run UTS
      run: ./scripts/run_uts.sh