name: Run Tests in Docker Container

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Możesz wybrać inny system operacyjny, np. `ubuntu-latest` lub `windows-latest`
    
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2  # Sprawdza kod z repozytorium

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # Ustawia Docker Buildx dla bardziej zaawansowanego builda
    
    - name: Build the Docker image
      run: |
        docker build -t my-test-image .devcontainer/  # Zbuduj obraz z Twojego Dockerfile
        docker run --name my-test-container my-test-image  # Uruchom kontener

    - name: Run tests
      run: |
        docker exec my-test-container bash -c "cd /workspace && make test"  # Uruchom testy wewnątrz kontenera
        docker rm -f my-test-container  # Usuwa kontener po wykonaniu testów
