name: Run Tests in Docker Container

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Możesz wybrać inny system operacyjny, np. `ubuntu-latest` lub `windows-latest`
    
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build the Docker image
      run: |
        docker build -t ghcr.io/gmalacho/testdocker -f Dockerfile .

    - name: Run the Docker image
      run: |
        docker run --rm -v .:/workspace ghcr.io/gmalacho/testdocker /bin/bash -c "./scripts/build.sh && cd ./build/ && ctest"
      
