name: CI

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
    - name: Say Hello
      run: echo "Hello CI"
    - name: Build
      run: echo "./scripts/build.sh"
    - name: Run UTS
      run: echo "./scripts/run_uts.sh"

