name: Dev Container CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Dev Container
        uses: devcontainers/ci@v3

      - name: Build and Start Dev Container
        run: devcontainer up --workspace-folder .

      - name: Run tests
        run: devcontainer exec --workspace-folder . pytest tests/
