name: CI

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  Run-UTS:
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/vscode/devcontainers/cpp:latest

    steps:
    - uses: actions/checkout@v2
    - name: Say Hello
      run: echo "Hello CI" ; pwd
    - name: Run build script
      run: ./scripts/build.sh
    - name: Run UTS
      run: ./scripts/run_uts.sh