name: Run Tests in Docker Container

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Możesz wybrać inny system operacyjny, np. `ubuntu-latest` lub `windows-latest`
    
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build the Docker image
      run: |
        docker build -t my-test-image .devcontainer/ 
        docker run --name my-test-container my-test-image

    - name: Run tests
      run: |
        docker exec my-test-container bash -c "cd /workspace && ./scripts/build.sh && ./scripts/run_uts.sh"
        docker rm -f my-test-container
