name: Run Tests in Docker Container

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Możesz wybrać inny system operacyjny, np. `ubuntu-latest` lub `windows-latest`
    
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build the Docker image
      run: |
        docker build -t my-test-image .devcontainer/ 

    - name: Run Docker container in background
      run: |
        docker run -d --name my-test-container my-test-image:latest  # Uruchamia kontener w tle
      
    - name: Execute commands in the running container
      run: |
        docker exec my-test-container bash -c "cd /workspace && ./scripts/build.sh && ./scripts/run_uts.sh"
      
    - name: Cleanup - Stop and remove the container
      run: |
        docker stop my-test-container  # Zatrzymuje kontener
        docker rm my-test-container    # Usuwa kontener
      
